"""Generate `docs/llms.txt`: the public API for models, from the catalog and signatures.

    python -m kinemo.docs.llms > docs/llms.txt
"""

from __future__ import annotations

import sys

import kinemo

from . import catalog, reference, signatures
from .entry import DocEntry
from .render import entry_signature, related_names

IMPORT_LINES = ("import kinemo as k", "")


def _example_body(entry: DocEntry) -> str:
    """The example without the `import kinemo as k` header every example shares."""
    lines = entry.example.rstrip("\n").splitlines()
    while lines and lines[0] in IMPORT_LINES:
        lines.pop(0)
    return "\n".join(lines)


def _header() -> list[str]:
    return [
        "# kinemo",
        "",
        "> Python library for explanatory animations (math, algorithms, engineering, data), "
        "with a native core in Rust. One form per concept, errors that come with fixes, and "
        "machine-readable tools (`check`, `inspect`, `snap`).",
        "",
        f"Version {kinemo.__version__} · IR {kinemo.IR_VERSION}. Generated by `python -m kinemo.docs.llms`; "
        "do not edit by hand.",
        "",
    ]


def _numbered(title: str, items: tuple[str, ...]) -> list[str]:
    return [f"## {title}", "", *[f"{i}. {text}" for i, text in enumerate(items, 1)], ""]


def _bullets(title: str, items: tuple[str, ...]) -> list[str]:
    return [f"## {title}", "", *[f"- {text}" for text in items], ""]


def _api() -> list[str]:
    out = [
        "## API",
        "",
        "Each symbol: signature, summary and one canonical example (all start with "
        "`import kinemo as k` and pass `kinemo check --strict`). Details: `kinemo docs <symbol>`.",
        "",
    ]
    shown_examples: dict[str, str] = {}
    for area, items in catalog.by_area().items():
        out += [f"### {area}", ""]
        for entry in items:
            out.append(f"#### `{entry_signature(entry)}`")
            related = related_names(entry)
            see_also = " See also: " + ", ".join(f"`{n}`" for n in related) + "." if related else ""
            out.append(entry.summary + see_also)
            first = shown_examples.get(entry.example)
            if first is not None:
                out.append(f"Example: same as `{first}`.")
            else:
                shown_examples[entry.example] = signatures.display_name(entry.symbol)
                out += ["```python", _example_body(entry), "```"]
        out.append("")
    return out


def _diagnostics() -> list[str]:
    from ..diagnostics import CATALOG

    out = [
        "## Diagnostics",
        "",
        "Every problem has a stable code, a location, an instant and, when possible, a fix in code "
        "(`kinemo check --fix` applies it). `kinemo explain <code>` gives the long explanation.",
        "",
        "| Range | Area |",
        "| --- | --- |",
        *[f"| {codes} | {area} |" for codes, area in reference.DIAGNOSTIC_RANGES],
        "",
        "Codes:",
        "",
    ]
    groups: dict[str, list[str]] = {}
    for code, item in sorted(CATALOG.items()):
        groups.setdefault(code[:3], []).append(f"`{code}` {item.title}")
    out += [f"- {' · '.join(items)}" for items in groups.values()]
    return out + [""]


def _manim() -> list[str]:
    rows = reference.manim_rows()
    return [
        "## Manim → kinemo",
        "",
        "Manim names are recognized and answered with the equivalent form (K11xx).",
        "",
        "| Manim | kinemo |",
        "| --- | --- |",
        *[f"| {row.manim} | {row.kinemo} |" for row in rows],
        "",
    ]


def generate() -> str:
    lines = (
        _header()
        + _numbered("Rules", reference.RULES)
        + _numbered("Recommended loop for agents", reference.AGENT_LOOP)
        + _bullets("Conventions", reference.CONVENTIONS)
        + _api()
        + _diagnostics()
        + _manim()
    )
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    sys.stdout.write(generate())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
