"""Type stub of the native core (`crates/kinemo-py`, built into `_core.abi3.so`).

The functions authors can reach are typed; `Builder` and `PreviewServer` are internal
(their many methods are reached only from typed kinemo code) and stay dynamic."""

from typing import Any, Callable, Sequence

IR_VERSION: str

class Builder:
    def __init__(self, config_json: str) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class PreviewServer:
    def __init__(self, port: int = 7878) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

def arrow_supported(obj: object) -> bool: ...
def arrow_column_f64(obj: object) -> list[float]: ...
def arrow_column_str(obj: object) -> list[str | None]: ...
def arrow_table_columns(obj: object) -> list[tuple[str, str, list[Any]]]: ...
def measure_text(text: str, size: float = 0.5) -> tuple[float, float, float, float]: ...
def ffmpeg_available() -> bool: ...
def render_movie(
    builders: Sequence[Builder],
    transitions: Sequence[tuple[str, float]],
    path: str,
    format: str = "mp4",
    quality: str = "final",
    progress: Callable[[int, int], object] | None = None,
) -> None: ...
