[package]
name = "kinemo-math"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kinemo-text.workspace = true
kurbo.workspace = true
ttf-parser.workspace = true
typst.workspace = true
typst-layout.workspace = true
typst-assets.workspace = true
comemo.workspace = true
mitex.workspace = true
mitex-spec-gen.workspace = true
fxhash.workspace = true
