[package]
name = "kinemo-resolve"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
kinemo-ir.workspace = true
kinemo-eval.workspace = true
kinemo-layout.workspace = true
kurbo.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
