"""Write THIRD_PARTY_LICENSES.md: the licenses of the Rust crates compiled into kinemo's
wheels, plus the bundled fonts. Each crate is listed with its copyright lines; the license
texts are reproduced once per distinct text (compared without the copyright lines).

    .venv/bin/python scripts/third_party_licenses.py

Reads `cargo metadata` and the license files each crate ships. The crates are the ones
`kinemo-py` (the Python extension) depends on, on every platform; the optional GPU backend is
listed separately because it is only in builds with `--features gpu`.
"""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "THIRD_PARTY_LICENSES.md"
LICENSE_NAMES = ("LICENSE", "LICENCE", "COPYING", "NOTICE", "UNLICENSE")


#: A copyright notice line: "Copyright (c) 2016 Name", "Copyright The Rust Project…", "© 2020 …";
#: not the license's own sentences that mention copyright.
COPYRIGHT = re.compile(r"^[ \t]*(?:(?:Copyright|COPYRIGHT)[ \t]*(?:\(c\)|\(C\)|©)?[ \t]*(?:\d{4}|[A-Z][a-z])|(?:\(c\)|\(C\)|©)[ \t]*\d{4}).*$", re.M)


def metadata(*features: str) -> dict:  # type: ignore[type-arg]
    run = subprocess.run(["cargo", "metadata", "--format-version", "1", *features], cwd=ROOT, capture_output=True, text=True, check=True, encoding="utf-8")
    return json.loads(run.stdout)


def without_copyright(text: str) -> str:
    """The license text with copyright lines removed, for comparing licenses across crates."""
    return re.sub(r"\s+", " ", COPYRIGHT.sub("", text)).strip()


def copyright_lines(texts: list[tuple[str, str]]) -> list[str]:
    seen: list[str] = []
    for _, text in texts:
        for line in COPYRIGHT.findall(text):
            line = line.strip()
            if line not in seen and "[yyyy]" not in line and "<year>" not in line:
                seen.append(line)
    return seen


def reachable(meta: dict, start: str) -> set[str]:  # type: ignore[type-arg]
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    seen: set[str] = set()
    stack = [start]
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        for dep in nodes[current]["deps"]:
            if any(kind["kind"] is None for kind in dep["dep_kinds"]):  # normal dependencies only
                stack.append(dep["pkg"])
    return seen


def license_texts(package: dict) -> list[tuple[str, str]]:  # type: ignore[type-arg]
    folder = Path(package["manifest_path"]).parent
    files = sorted(p for p in folder.iterdir() if p.is_file() and p.name.upper().startswith(LICENSE_NAMES))
    return [(p.name, p.read_text(errors="replace", encoding="utf-8").strip()) for p in files]


def main() -> int:
    default, everything = metadata(), metadata("--all-features")
    packages = {p["id"]: p for p in everything["packages"]}
    members = set(everything["workspace_members"])
    by_name = {packages[i]["name"]: i for i in members}
    extension = reachable(default, by_name["kinemo-py"]) - members
    gpu = reachable(everything, by_name["kinemo-py"]) - members - extension

    # Each distinct license text (compared without copyright lines) is printed once; crates
    # list their copyright lines and point at the texts they are under.
    texts: dict[str, str] = {}
    crates: list[str] = []
    for package_id in sorted(extension | gpu, key=lambda i: (packages[i]["name"], packages[i]["version"])):
        package = packages[package_id]
        files = license_texts(package)
        refs = []
        for _, text in files:
            key = without_copyright(text)
            if key not in texts:
                texts[key] = COPYRIGHT.sub("", text).strip()
            refs.append(list(texts).index(key) + 1)
        label = f"- **{package['name']}** {package['version']}, {package.get('license') or 'no SPDX expression'}"
        if package_id in gpu:
            label += " (GPU builds only)"
        label += ": " + (", ".join(f"[text {n}](#text-{n})" for n in refs) if refs else "no license file, see the SPDX expression")
        notices = copyright_lines(files)
        if notices:
            label += ". " + "; ".join(notices)
        crates.append(label)

    lines = [
        "# Third-party licenses",
        "",
        "kinemo's wheels contain compiled code from the Rust crates below. Each crate is listed with",
        "its license and copyright lines; the license texts follow, each one once. Generated by",
        "`scripts/third_party_licenses.py`.",
        "",
        "ffmpeg is not bundled: kinemo runs the `ffmpeg` program installed on the system.",
        "",
        "## Fonts",
        "",
        "The DejaVu fonts in `assets/fonts/` (embedded in the wheels) follow",
        "[`assets/fonts/LICENSE_DEJAVU`](assets/fonts/LICENSE_DEJAVU).",
        "",
        "## Crates",
        "",
        *crates,
        "",
        "## License texts",
        "",
    ]
    for n, text in enumerate(texts.values(), start=1):
        lines += [f'<a id="text-{n}"></a>', "", f"### Text {n}", "", "```text", text, "```", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(extension)} crates in the extension, {len(gpu)} more with the GPU backend, {len(texts)} distinct texts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
