"""Markdown primitives shared by every reference page, and writing the pages to disk."""

from __future__ import annotations

import os
import re
from collections.abc import Iterable, Sequence

#: Banner at the top of every generated page.
GENERATED_NOTICE = "<!-- Generated by `python -m kinemo.docs.markdown docs/reference`; do not edit by hand. -->"

#: Signatures longer than this are written with one parameter per line.
SIGNATURE_WIDTH = 88


def slug(text: str) -> str:
    """Anchor-safe text: lowercase letters, digits, `_` and `-` (`Scene.play` → `scene-play`)."""
    lowered = re.sub(r"[^a-z0-9_]+", "-", text.lower())
    return lowered.strip("-")


def anchor(identifier: str) -> str:
    """An explicit HTML anchor, stable whatever the heading text is."""
    return f'<a id="{identifier}"></a>'


def heading(level: int, text: str, identifier: str | None = None) -> list[str]:
    lines = [anchor(identifier)] if identifier else []
    return [*lines, f"{'#' * level} {text}", ""]


def code(text: str) -> str:
    """Inline code that survives backticks inside `text`."""
    if "`" not in text:
        return f"`{text}`"
    return f"`` {text} ``"


def code_block(text: str, language: str = "python") -> list[str]:
    return [f"```{language}", text.rstrip("\n"), "```", ""]


def link(text: str, target: str) -> str:
    return f"[{text}]({target})"


def cell(text: str) -> str:
    """Text safe inside a table cell (pipes escaped, on one line)."""
    return " ".join(str(text).split()).replace("|", "\\|") or " "


def table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    rows = list(rows)
    if not rows:
        return []
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(" --- " for _ in header) + "|"]
    lines += ["| " + " | ".join(cell(value) for value in row) + " |" for row in rows]
    return [*lines, ""]


def paragraphs(text: str) -> list[str]:
    """A docstring as Markdown paragraphs (single newlines inside a paragraph are joined)."""
    out: list[str] = []
    for block in text.strip().split("\n\n"):
        lines = block.splitlines()
        if all(line.startswith("    ") or not line.strip() for line in lines):
            out += code_block("\n".join(line[4:] for line in lines))
        else:
            out += [" ".join(" ".join(lines).split()), ""]
    return out


def page(title: str, intro: str, body: list[str]) -> str:
    lines = [GENERATED_NOTICE, "", f"# {title}", ""]
    if intro:
        lines += [intro, ""]
    lines += body
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.rstrip("\n") + "\n"


def write_pages(pages: dict[str, str], out_dir: str) -> list[str]:
    """Write `{file name: content}` into `out_dir` and return the written paths."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name, content in sorted(pages.items()):
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        written.append(path)
    return written
